environment:
  package_semantic_version: 6.0.0
  assembly_semantic_version: 6.0.0

version: $(package_semantic_version).{build}

skip_tags: true

image: Visual Studio 2019

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(assembly_semantic_version).0'
  assembly_file_version: '$(appveyor_build_version)'
  assembly_informational_version: '$(package_semantic_version)-CI-{build}'

configuration: Release

before_build:
- nuget restore

build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: false

deploy:
- provider: NuGet
  server: https://www.myget.org/F/autofac/
  api_key:
    secure: rCUEY75fXN0wxtMy6QL4jCrLdaYbxIBzIXWeN+wEu/XDpyqimzreOc5AH5jMd5ah
  symbol_server: https://nuget.symbolsource.org/MyGet/autofac
